---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foodstock-pv
  labels:
    app: foodstock
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foodstock-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: foodstock-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodstock-api
  labels:
    app: foodstock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodstock-api
  template:
    metadata:
      labels:
        app: foodstock-api
    spec:
      volumes:
        - name: dbdata
          persistentVolumeClaim:
            claimName: foodstock-pvc
      containers:
        - name: foodstock-api
          image: stephanelucienvauthier/foodstock-api:0.1.2
          volumeMounts:
            - mountPath: "/usr/src/app/data"
              name: dbdata
---
apiVersion: v1
kind: Service
metadata:
  name: foodstock-api-srv
spec:
  selector:
    app: foodstock
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: foodstock-ingress
spec:
  rules:
    - host: foodstock-api.pytech.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: foodstock-api-srv
              servicePort: 8000
---
